services:
  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lobo_guara
    ports:
      - '5432:5432'
    volumes:
      - lobo_guara_data:/var/lib/postgresql/data

volumes:
  lobo_guara_data:
